name: Shooter CI

on:
  push:
    branches: [ "main", "jake-dev" ]
  pull_request:
    branches: [ "main", "jake-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install valgrind shaderc
        
      
    - name: make
      run: make
