name: Shooter CI

on:
  push:
    branches: [ "main", "jake-dev", "ben-dev", "eklipsed" ]
  pull_request:
    branches: [ "main", "jake-dev", "ben-dev", "eklipsed" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make ccid
