name: Shooter CI

on:
  push:
    branches: [ "main", "jake-dev", "eklipsed" ]
  pull_request:
    branches: [ "main", "jake-dev", "eklipsed" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        git submodule update --remote
        make
